### ISSUE TITLE
Graalvm is not supported out of the box

### ISSUE THREAD

**Issue by bugbuilder** [micronaut-projects/micronaut-kubernetes#107]
To make possible to use micronaut-kubernetes with graalvm is necessary to add the following typehint
```
@TypeHint(
        value = {
                io.micronaut.kubernetes.client.v1.Port.class,
                io.micronaut.kubernetes.client.v1.Address.class,
                io.micronaut.kubernetes.client.v1.KubernetesObject.class,
                io.micronaut.kubernetes.client.v1.Metadata.class,
                io.micronaut.kubernetes.client.v1.endpoints.Endpoints.class,
                io.micronaut.kubernetes.client.v1.endpoints.EndpointsList.class,
                io.micronaut.kubernetes.client.v1.endpoints.EndpointsSubset.class,
                io.micronaut.kubernetes.client.v1.services.Service.class,
                io.micronaut.kubernetes.client.v1.services.ServiceList.class,
                io.micronaut.kubernetes.client.v1.services.ServiceSpec.class,
                io.micronaut.kubernetes.client.v1.pods.ContainerStatus.class,
                io.micronaut.kubernetes.client.v1.pods.Pod.class,
                io.micronaut.kubernetes.client.v1.pods.PodStatus.class,
                io.micronaut.kubernetes.client.v1.secrets.Secret.class,
                io.micronaut.kubernetes.client.v1.secrets.SecretList.class,
                io.micronaut.kubernetes.client.v1.configmaps.ConfigMap.class,
                io.micronaut.kubernetes.client.v1.configmaps.ConfigMapList.class,
                io.micronaut.kubernetes.client.v1.configmaps.ConfigMapWatchEvent.class,
        },
        typeNames = {
                "io.micronaut.caffeine.cache.SSAW",
                "io.micronaut.caffeine.cache.PSAW"
        },
        accessType = {
                TypeHint.AccessType.ALL_DECLARED_CONSTRUCTORS,
                TypeHint.AccessType.ALL_PUBLIC_METHODS,
                TypeHint.AccessType.ALL_DECLARED_FIELDS
        }
)
public class Application {

    public static void main(String[] args) {
        Micronaut.run(Application.class);
    }
}
```
it would be great to add this settings to reflection-config.json to make it easier to use.

**Comment by ilopmar** [comment]
The caffeine classes are already defined in micronaut-core for [master](https://github.com/micronaut-projects/micronaut-core/blob/master/core/src/main/resources/META-INF/native-image/io.micronaut.core/cache-caffeiene-graal/reflection-config.json) and [1.3.x](https://github.com/micronaut-projects/micronaut-core/blob/1.3.x/core/src/main/resources/META-INF/native-image/io.micronaut.core/cache-caffeiene-graal/reflection-config.json) branches.

**Comment by bugbuilder** [comment]
Sandy doesn't works

**Comment by bugbuilder** [comment]
Or maybe is a issue when you use kubernetes and jwt modules, because that was I did.

**Comment by ilopmar** [comment]
Those `io.micronaut.caffeine` classes were included after 1.3.5 was released. If you try with Micronaut 1.3.6 (which was released yesterday) you won't need to define those 2.
We will add all the missing kubernetes classes to the graalvm configuration.

**Comment by bugbuilder** [comment]
Yep the problem with caffeine was in 1.3.5. In 1.3.6 is working, my bad I didn't check the last version, but this fixing it doesn't listed in the [milestone](https://github.com/micronaut-projects/micronaut-core/milestone/47?closed=1) because of that is a little tricky to check the new fixes in new version, implement a Changelog it would be great.

Thanks for add the missing classes.

**Comment by ilopmar** [comment]
We're working on improving our release notes to automatically include everything. In some modules we've done the change and we plan to do it in the rest of the modules soon. Thanks for your feedback :-)
