### ISSUE TITLE
Question: GraalVM and Kubernetes

### ISSUE THREAD

**Issue by paulvi** [micronaut-projects/micronaut-kubernetes#17]
What is relation is to be between GraalVM and Kubernetes?

Graal is JVM based with runtime images just jar file.  
While Kubernetes has been container managing runtime, starting as docker alternative.

It seems to me that they are offerings from different vendors: Oraclle and Google, 
and maybe will not always work well together, if backing companies relation deteriorates again.

**Comment by sdelamo** [comment]
Thanks for the question @paulvi 

However, I encourage you to post this question to our Gitter community. 

https://gitter.im/micronautfw

see: https://micronaut.io/faq.html

I am going to close this issue since we aim to keep Github issues just for bugs, enhancement requests etc
