### ISSUE TITLE
Feature Request: Flexible kubernetes client authentication methods

### ISSUE THREAD

**Issue by viniciusccarvalho** [micronaut-projects/micronaut-kubernetes#173]
The current method of authenticating with the kubernetes API via the secret mounted on `/var/run/secrets/kubernetes.io/serviceaccount/token` makes it very hard to test, or use the kubernetes client low level client outside of a k8s environment. The fabric8 client has a flexible way to provide the token, the ca mount taking the least precedence:

https://github.com/fabric8io/kubernetes-client#configuring-the-client

Would be nice to have a similar way to have a default of reading the file, but allowing an environment variable or use kube config to pull the token.

**Comment by pgressa** [comment]
Closing this issue as it is already fixed by using official K8s java sdk client.
