### ISSUE TITLE
Feature Request: Service Discovery across multiple namespaces

### ISSUE THREAD

**Issue by jaksah** [micronaut-projects/micronaut-kubernetes#181]
From my understanding the discovery client only discovers services within the _single_ namespace that's configured, either by default value or explicitly setting the config. We have a use case where we would need service discovery across multiple namespaces. For example:

`FooService` named `foo` running in namespace `A`
`BarService` named `bar` running in namespace `A` 
`BazService` named `baz` running in namespace `B`

From `FooService` we want to use a `@Client("${bar.clientid:bar}") BarClient` to call `BarService` and `@Client("${baz.clientid:baz}") BazClient` to call `BazService`.

Is this something can could be achieved solely by extending the kubernetes discovery client or would it require some underlying changes in the kubernetes cluster?

**Comment by alvarosanchez** [comment]
It shouldn't be too difficult to change https://github.com/micronaut-projects/micronaut-kubernetes/blob/master/kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/discovery/KubernetesDiscoveryClient.java#L84 to search in all namespaces. PRs welcomed

**Comment by pgressa** [comment]
@alvarosanchez imho this could potentially end up in lot of 403s if micronaut service account is not authorised to get Services. But by default it could do the job, but I would extend it with namespace filtering, similarly like it's for service filtering. Anyway, in my opinion we should also distinguish service namespaces in the annotation liek `@Client('<namespace>.<service-name>')`.

**Comment by alvarosanchez** [comment]
The 403s can also happen even for the default namespace. I expect someone wanting to call services across namespaces to understand it needs permissions. Hence, I wrote https://micronaut-projects.github.io/micronaut-kubernetes/latest/guide/#_kubernetes_api_authentication. It should be a matter of explaining it there.

Regarding namespace filtering, I see it problematic. The Kubernetes API lets you search either within a concrete namespace, or all. If you were to have includes/excludes, you would need to make several API calls to retrieve the list of namespaces first, then for each retrieve the list of services. And the service discovery is refreshed every 30 seconds.

A better option would be specifying the namespace in the annotation as you suggested (I'd rather avoid using a dot as separator, so maybe `@Client("<namespace>#<service-name>")`). That way you only search on that namespace.

**Comment by pgressa** [comment]
Yeah, if we would make it like mandatory to define the namespace in the annotation to distinguish the target namespace, then the filtering is useless. 👍

**Comment by alvarosanchez** [comment]
It doesn't need to be mandatory though. One could have `@Client("my-service")` (which would target the default namespace) and `@Client("my-ns#my-service")`

**Comment by pgressa** [comment]
sure sure, that was my idea, I meant mandatory in case you want to discovery service from other then app configured namespace.

**Comment by jaksah** [comment]
How would using `#` as separator propagate to the client configuration? Lets say you would like to set the read timeout for the client
```
micronaut.http.services.my-ns#my-service.read-timeout=PT5S
```
Thinking that `#` is considered a comment in `.yaml` and `.properties` files.

**Comment by pgressa** [comment]
@jaksah we spoke about this with @alvarosanchez and at this moment we agreed that the namespace will be part of configuration like:
```
kubernetes:
  client:
    discovery:
      services:
        my-service:
          namespace: my-ns
```

**Comment by pgressa** [comment]
Closing addressed in https://github.com/micronaut-projects/micronaut-kubernetes/pull/191
