### ISSUE TITLE
k8s cold boot time super slow due too many ENV_VARS_USING_UNDESCORES

### ISSUE THREAD

**Issue by pontello** [micronaut-projects/micronaut-kubernetes#209]
> Because the number of properties generated is exponential based on the number of _ characters in the environment variable, it is recommended to refine which, if any, environment variables are included in configuration if the number of environment variables with a large number of underscores is high.

Above is a quote from [official docs](https://docs.micronaut.io/latest/guide/index.html#propertySource) describing how env variables are treated. Even tough well documented there it took me a while to understand why my projects were taking longer than expected during boot time and a way to work it around.

If you deploy micro services in a K8s cluster you may have seen variables similar to bellow ones when executing **env** command from inside a container:

```
V1_SERVICE_XPTO_SERVICE_HOST=172.20.232.70
V1_SERVICE_XPTO_PORT_8080_TCP_ADDR=172.20.232.70
V1_SERVICE_XPTO_PORT_8080_TCP=tcp://172.20.232.70:8080
V1_SERVICE_XPTO_SERVICE_PORT_HTTP=8080
```

A bunch of envs like above will be added for every deployment that belongs to the same cluster. You may have performance issues while deploying micronaut apps in a large k8s cluster because of how it handle env variables composed by many underscores. It will also consume more memory to index many combinations that were completely useless for my use cases.

I have solved this problem by creating a custom `PropertySource` that skips the garbage produced by k8s:

```java
public class MicronautEnvPropertySource extends MapPropertySource {

    public static final MicronautEnvPropertySource INSTANCE = new MicronautEnvPropertySource();

    private MicronautEnvPropertySource() {
        super("filtered-envs", filter(System.getenv()));
    }

    @Override
    public PropertyConvention getConvention() {
        return ENVIRONMENT_VARIABLE;
    }

    @VisibleForTesting
    static final Map<String, String> filter(Map<String, String> envs) {

        var props = new HashMap<String, String>();

        for (var entry : envs.entrySet()) {
            // Filter out K8S boilerplate envs due to how micronaut resolve envs.
            // https://docs.micronaut.io/latest/guide/index.html#propertySource
            if (!entry.getKey().endsWith("80_TCP")
                    && !entry.getKey().endsWith("_TCP_PORT")
                    && !entry.getKey().endsWith("_TCP_PROTO")
                    && !entry.getKey().endsWith("_TCP_ADDR")
                    && !entry.getKey().endsWith("_UDP_PORT")
                    && !entry.getKey().endsWith("_UDP_PROTO")
                    && !entry.getKey().endsWith("_UDP_ADDR")
                    && !entry.getKey().endsWith("_SERVICE_PORT")
                    && !entry.getKey().endsWith("_SERVICE_PORT_HTTP")
                    && !entry.getKey().endsWith("_SERVICE_HOST")
                    && (!entry.getKey().endsWith("_PORT") && !entry.getValue().startsWith("tcp://"))
            ) {
                props.put(entry.getKey(), entry.getValue());
            }
        }

        return props;
    }
}

```

Next step is to disable _built in_ env property source and plug the new one:

```java
Micronaut.build(args)
     .mainClass(Application.class)
     .environmentPropertySource(false)
     .propertySources(MicronautEnvPropertySource.INSTANCE)
     .start();
```

I have opened this issue so we can discuss if there is a better way to have this problem solved. If there is no other way than whoever is suffering from the same issue can benefit from the work around explained above. Please note that `environmentVariableIncludes` and `environmentVariableExcludes` didn't work for me because the patterns I have are related to sufixes and I don't  know all variable names in advance.

**Comment by graemerocher** [comment]
One idea could be to include such a property source as you have defined if the environment is `k8s`

**Comment by alvarosanchez** [comment]
@pontello you made a good point and I think it's worth fixing it.

I see 2 options:

1. Include the property source in `micronaut-kubernetes`, and document the `Micronaut.build()` business.
2. Include the property source in `micronaut-core` and make the `k8s` env case in `DefaultEnvironment`

@graemerocher thoughts?

**Comment by graemerocher** [comment]
I guess if it is included in core then we don't have to document the `Micronaut.build()` business which is better

**Comment by alvarosanchez** [comment]
Correct, that was the idea, saving users from that so that `Micronaut.run()` simply works.

**Comment by alvarosanchez** [comment]
@pontello since you are the author of that code, are you willing to contribute a PR with that property source to micronaut-core and conditionally configure it in `DefaultEnvironment`?

**Comment by pontello** [comment]
Unfortunately I can't @alvarosanchez, I am in the middle of a rush... 

Please feel free to take it from here and don't worry about myself being the author...

Thanks

**Comment by David-16** [comment]
@alvarosanchez I get that the number of underscores increases the number of possibilities by a power of 2 every time, but the worst offender in this case is `V1_SERVICE_XPTO_PORT_8080_TCP_ADDR` which has 6 underscores resulting in 64 possibilities of `-` and/or `.`

Assuming high water marks of 10 such properties for each service and 100 such services, this is 64,000

I think this count can be naively reduced by an order of 4 by simply assuming `BLAH_TCP_ADDR` etc always resolves to `blah.tcp-addr`.  Almost all these properties have 2 underscores which I think can be assumed to be fixed in meaning.  This moves the high water mark to 16,000

I think careful and reasonable assumptions could reduce the exponential (or power I can never remember which) expansion by many orders of magnitude.  For example, `FOO_BAR_SERVICE_HOST` could be assumed to always resolve to `foo-bar.service.host` which is constant time

You could further augment the read resolution to catch any breakages of this assumption (e.g., if looking up `foo.bar.service.host` you would print a message saying see this page for details about this optimization).  This would be nice to have but might be a bit of a shoe-horn depending how the code is structured
