### ISSUE TITLE
Micronaut fails to start if configmap is loaded with no data elements

### ISSUE THREAD

**Issue by amckee23** [micronaut-projects/micronaut-kubernetes#231]
Spotted today on Micronaut 2.0.2 but by looking at the code its likely this issue is also on latest.  It looks like when an empty config map is loaded there is a missing null guard on configMapAsPropertySource within KubernetesUtils.java which leads to a null pointer exception on application startup.  Specifically:
 ```Map.Entry<String, String> entry = data.entrySet().iterator().next();```

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Create a config map with no data elements in it:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-cm
  labels:
    app: example-app
data: {}
```

Load the config map in a micronaut app:
bootstrap.yml
```
micronaut:
  config-client:
    enabled: true
kubernetes:
  client:
    config-maps:
      watch: true
      includes:
        - example-cm
```

### Expected Behaviour

The application should start

### Actual Behaviour

The application fails to start and returns a null exception on startup:
```
Envoy Ready continuing...
17:03:14[main][][INFO]i.m.c.e.DefaultEnvironment:: Established active environments: [k8s, cloud]
17:03:14[main][][INFO]i.m.c.e.DefaultEnvironment:: Established active environments: [k8s, cloud]
17:03:14[main][][INFO]i.m.c.DefaultBeanContext:: Reading Startup environment from bootstrap.yml
17:03:17[main][][ERROR]i.m.r.Micronaut:: Error starting Micronaut server: null
java.util.NoSuchElementException: null
	at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.base/java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.base/java.util.HashMap$EntryIterator.next(Unknown Source)
	at io.micronaut.kubernetes.util.KubernetesUtils.configMapAsPropertySource(KubernetesUtils.java:62)
```

### Environment Information

- **Operating System**: AKS (Replicated in EKS)
- **Micronaut Version:** 2.0.2
- **JDK Version:** 11

**Comment by pgressa** [comment]
https://github.com/micronaut-projects/micronaut-kubernetes/pull/239
