### ISSUE TITLE
Support loading configuration from Kubernetes configmaps and secrets 

### ISSUE THREAD

**Issue by codependent** [micronaut-projects/micronaut-kubernetes#25]
The only thing that prevents my organization from starting using micronaut is property loading. Currently our Spring Boot apps load their properties from k8s configmaps and secrets using spring cloud config kubernetes: https://github.com/spring-cloud/spring-cloud-kubernetes

Could this integration be added to Micronaut?

**Comment by alvarosanchez** [comment]
This is already implemented in the latest snapshot:

https://micronaut-projects.github.io/micronaut-kubernetes/snapshot/guide/

**Comment by codependent** [comment]
Great!! Thanks guys
