### ISSUE TITLE
`kubernetes.client.read-idle-timeout` setting does not seem to be taken into account by `KubernetesConfigMapWatcher`

### ISSUE THREAD

**Issue by rdesgroppes** [micronaut-projects/micronaut-kubernetes#302]
### Steps to Reproduce

1. Observe that `KubernetesConfigMapWatcher` installed stream always times out after exactly 5 minutes without event:
   ```
   io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | io.micronaut.http.client.exceptions.ReadTimeoutException: Read Timeout
   ```
2. Try setting `kubernetes.client.read-idle-timeout` to `0s` or a negative duration, in either `bootstrap.yml` or `application.yml`
3. Redeploy.

### Expected Behaviour

The `KubernetesConfigMapWatcher` installed stream doesn't time out.

### Actual Behaviour

The `KubernetesConfigMapWatcher` installed stream still times out after 5 minutes without event.

Are [Configuration Properties for KubernetesConfiguration](https://micronaut-projects.github.io/micronaut-kubernetes/snapshot/guide/#io.micronaut.kubernetes.client.v1.KubernetesConfiguration) applicable to the `KubernetesClient` used by `KubernetesConfigMapWatcher`?

### Environment Information

- **Micronaut Version:** `2.5.3`

**Comment by pgressa** [comment]
@rdesgroppes I'm closing this issue b/c since the v3 we use official k8s client and the configuration of the underlying OkHttpClient is configurable using bean listener:
```java
@Singleton
public class ApiClientListener implements BeanCreatedEventListener<ApiClient> {

    @Override
    public ApiClient onCreated(BeanCreatedEvent<ApiClient> event) {
        ApiClient apiClient = event.getBean();
        OkHttpClient okHttpClient = apiClient.getHttpClient().newBuilder()
                .readTimeout(5345, TimeUnit.MILLISECONDS)
                .build();
        apiClient.setHttpClient(okHttpClient);
        return apiClient;
    }
}
```
