### ISSUE TITLE
micronaut-kubernetes-informer prevents BeanCreatedEventListener<ApiClient> from firing

### ISSUE THREAD

**Issue by sosguthorpe** [micronaut-projects/micronaut-kubernetes#435]
### Expected Behavior

Implementation of BeanCreatedEventListener<ApiClient> should be called.

### Actual Behaviour

Implementation of BeanCreatedEventListener<ApiClient> seems to be ignored

### Steps To Reproduce

See: Example Application

Running ./gradlew check causes second test to fail.

Downgrading micronaut version to below 3.3.x (3.2.7) - Tests pass
Removing dependency on `io.micronaut.kubernetes:micronaut-kubernetes-informer` - Tests pass.

### Example Application

https://github.com/sosguthorpe/mn-kube-informer-events

### Version

3.3.x

**Comment by timyates** [comment]
Seems to be the `micronaut-kubernetes-informer:ResourceEventHandlerBeanListener` that is causing the issue...  Investigating...
