### ISSUE TITLE
Move examples to guides

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-kubernetes#442]
### Issue description

We should remove the examples from here, after we have captured them as guides

**Comment by alvarosanchez** [comment]
Note the examples are really test applications, with tests that are part of the whole module build

**Comment by timyates** [comment]
@alvarosanchez Good call... Maybe just `micronaut-kubernetes-client` as it has no tests...

Or maybe we should just add tests...  @sdelamo what's the thinking here?  Just examples with no tests?

**Comment by timyates** [comment]
I see now after looking deeper...these examples are used in the tests as Pods 👍

**Comment by sdelamo** [comment]
@timyates lets leave the examles in the repository fi they are are used for tests but pelase create issues in the guides repository to create guides. We don't have any K8s guides yet.

**Comment by timyates** [comment]
@sdelamo raised https://github.com/micronaut-projects/micronaut-guides/issues/846 and assigned it to me
