### ISSUE TITLE
Add support for Dekorate

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-kubernetes#46]
https://github.com/dekorateio/dekorate

**Comment by piomin** [comment]
I think it would be very nice addition

**Comment by pgressa** [comment]
Support for 1.0.1 for starter-project https://github.com/micronaut-projects/micronaut-starter/pull/446

**Comment by alvarosanchez** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-starter/pull/446
