### ISSUE TITLE
ConfigMapLabelSupplier tries to initialize when eagerInitSingletons property is set to true

### ISSUE THREAD

**Issue by Ksnz** [micronaut-projects/micronaut-kubernetes#479]
### Expected Behavior

`ConfigMapLabelSupplier` shouldn't be initialized when it's not a k8s environment

### Actual Behaviour

`ConfigMapLabelSupplier` still tries to initialize in not k8s environment when eagerInitSingletons property is set to true because there is no any `@Requires` condition for that bean

### Steps To Reproduce

Add `implementation("io.micronaut.kubernetes:micronaut-kubernetes-discovery-client")` to the project
Run
```
Micronaut.build((String[]) null)
            .eagerInitSingletons(true)
            .eagerInitConfiguration(true)
            .start();
```
Get 
```
Error starting Micronaut server: Bean definition [io.micronaut.kubernetes.configuration.ConfigMapLabelSupplier] could not be loaded: Failed to inject value for parameter [configuration] of class: io.micronaut.kubernetes.configuration.ConfigMapLabelSupplier
```

### Version

3.4.2

**Comment by graemerocher** [comment]
Seems like an easy fix and just adding https://github.com/micronaut-projects/micronaut-kubernetes/blob/21219be67b20c07dde522d3fc75cbf99de2a448a/kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/configuration/KubernetesConfigMapWatcher.java#L54 to the type.

Want to send a PR?

**Comment by Ksnz** [comment]
> Want to send a PR?

I'll try :)

**Comment by Ksnz** [comment]
@graemerocher could you approve PR workflows?

**Comment by GavrilovSV** [comment]
@alvarosanchez 
Could you please release the new version of `micronaut-kubernetes` to make this fix available? The latest release was in march
