### ISSUE TITLE
Enable config option for KubernetesConfigMapWatcher 

### ISSUE THREAD

**Issue by Xaseron** [micronaut-projects/micronaut-kubernetes#72]
We have a CI/CD Jenkins Pipeline that runs the build and test tasks on an OpenShift pod. This pod does not have the access rights to list the configMaps. It would be great to disable the ConfigMapWatcher.
So we can get rid off these exceptions in the Unit Tests:
```
 13:20:50.441 [nioEventLoopGroup-3-3] ERROR i.m.k.c.KubernetesConfigMapWatcher - Error while watching ConfigMap events
    io.micronaut.http.client.exceptions.HttpClientResponseException: Forbidden
```

**Comment by Xaseron** [comment]
Thank you for your fast fix for this issue. I've tested it and i had to put this configuration into the bootstrap.yml. If i put the config in the application.yml then i still get on exception before the application.yml gets parsed. Maybe this should be added to the documentation?

**Comment by alvarosanchez** [comment]
Sure! PRs welcomed.
