### ISSUE TITLE
document kubernetes-client-openapi module

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-kubernetes#783]
We introduced a new module, `kubernetes-client-openapi` in https://github.com/micronaut-projects/micronaut-kubernetes/pull/762.

 However, it is not documented. We need to document new features and modules; otherwise, Micronaut users will not be able to discover those features.

**Comment by msupic** [comment]
@sdelamo - The module has been documented here: https://github.com/micronaut-projects/micronaut-kubernetes/blob/6.2.x/src/main/docs/guide/kubernetes-client-openapi.adoc
