### ISSUE TITLE
Evaluate /var/run/secrets/kubernetes.io/serviceaccount/namespace to get default namespace if none is configured

### ISSUE THREAD

**Issue by koebbingd** [micronaut-projects/micronaut-kubernetes#95]
At the moment you have to configure which namespace to use. If none is configured "default" is assumed.
The namespace the pod is deployed in is available under /var/run/secrets/kubernetes.io/serviceaccount.

What about using that namespace as default if none is given -> less configuration (at least in my case).

I'd like to contribute that. How can I do it?

**Comment by alvarosanchez** [comment]
What you're asking for is already implemented, and documented:

![image](https://user-images.githubusercontent.com/153880/75657008-8ae5f500-5c65-11ea-935a-c3a0c12750d3.png)

**Comment by koebbingd** [comment]
Now that I had a second look I wonder how I could have overlooked it!
